name       : budgie-cputemp-applet
version    : 1.2.0
release    : 2
source     :
    - https://github.com/tarkah/budgie-cputemp-applet/archive/refs/tags/1.2.0.tar.gz : f3c897dc47a08398f1da0b1bb020d7fe07d01b93666ea6f48623990184a8325a
license    : GPL-2.0-only
component  : desktop.budgie
summary    : Applet to monitor CPU Temperature
description: |
    An applet that monitors and displays CPU Temperature. Sensor can be chosen in the applet popover menu.
builddeps  :
    - pkgconfig(budgie-1.0)
    - vala
setup      : |
    %meson_configure --sysconfdir=/usr/share
build      : |
    %ninja_build
install    : |
    %ninja_install
